import Head from 'next/head'
import styles from '../styles/Home.module.css'
import PageHeader from '../React-Components/PageHeader';

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Codex Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <PageHeader />
          {/* TODO: Navigation bar */}
          {/* TODO: Content */}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const data = null;
  return {
    props: {data}
  }
}
