import Head from 'next/head';
import Link from 'next/link';
import PageFooter from '../React-Components/PageFooter';
import PageHeader from '../React-Components/PageHeader';

import styles from '../styles/Login.module.css';

const Login = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Codex Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageHeader />
            <main className={styles.main}>
                <section className={styles.bodyContainer}>
                    <h1>Login to your account.</h1>
                    <form className={styles.loginForm}>
                        <div className={styles.inputField}>
                            <p>Username:</p>
                            <input type='username'/>
                        </div>
                        <div className={styles.inputField}>
                            <p>Password:</p>
                            <input type='password'/>
                        </div>
                        <button className={styles.formButton}>Log In</button>
                    </form>
                </section>
            </main>
            <PageFooter />
        </div>
    );
};

export default Login;
